# Generated by Django 4.1.6 on 2023-05-09 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('anm_id', models.IntegerField(primary_key=True, serialize=False)),
                ('anm_name', models.CharField(max_length=45)),
                ('anm_spcs', models.CharField(max_length=45)),
                ('anm_city', models.CharField(max_length=45)),
                ('anm_sex', models.CharField(max_length=20)),
                ('anm_rct', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'animal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('area_id', models.IntegerField(primary_key=True, serialize=False)),
                ('area_name', models.CharField(max_length=20)),
                ('area_loc', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'area',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des_img', models.TextField()),
                ('des_food', models.CharField(max_length=45)),
                ('des_bf', models.IntegerField()),
                ('des_lch', models.IntegerField()),
                ('des_dnn', models.IntegerField()),
                ('des_mdc', models.IntegerField()),
                ('des_mmdc', models.IntegerField(blank=True, null=True)),
                ('des_lmdc', models.IntegerField(blank=True, null=True)),
                ('des_dmdc', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'description',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('log_id', models.IntegerField(primary_key=True, serialize=False)),
                ('log_con', models.CharField(max_length=100)),
                ('log_dt', models.DateTimeField()),
            ],
            options={
                'db_table': 'log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('zone_id', models.IntegerField(primary_key=True, serialize=False)),
                ('zone_name', models.CharField(max_length=20)),
                ('zone_max', models.IntegerField()),
                ('zone_loc', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'zone',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zookeeper',
            fields=[
                ('zkp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('zkp_name', models.CharField(max_length=11)),
                ('zkp_call', models.CharField(max_length=11)),
                ('zkp_carr', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'zookeeper',
                'managed': False,
            },
        ),
    ]
